openapi: 3.0.0
info:
  title: Multichannel Notification API
  description: API REST para registrar usuarios y enviar notificaciones a través de múltiples canales.
  version: 1.0.0
servers:
  - url: http://localhost:5000
    description: Servidor local

paths:
  /users:
    post:
      summary: Registrar un usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                preferred_channel:
                  type: string
                available_channels:
                  type: array
                  items:
                    type: string
              required:
                - name
                - preferred_channel
                - available_channels
      responses:
        '201':
          description: Usuario registrado correctamente
        '400':
          description: Datos incompletos

    get:
      summary: Listar usuarios
      responses:
        '200':
          description: Lista de usuarios registrados
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    preferred_channel:
                      type: string
                    available_channels:
                      type: array
                      items:
                        type: string

  /notifications/send:
    post:
      summary: Enviar una notificación a un usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                message:
                  type: string
                priority:
                  type: string
              required:
                - user_name
                - message
                - priority
      responses:
        '200':
          description: Notificación enviada con éxito
        '404':
          description: Usuario no encontrado
        '500':
          description: Fallo en todos los canales disponibles
