services:
  notification-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multichannel-notification-system
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    networks:
      - notification-network

networks:
  notification-network:
    driver: bridge