openapi: 3.0.0
info:
  title: Multichannel Notification System API
  version: 1.0.0
  description: >
    REST API to register users and send multichannel notifications (email, SMS, console).
    Uses Chain of Responsibility for channel fallback and a Singleton logger for recording attempts.
servers:
  - url: http://localhost:5000

paths:
  /users:
    post:
      summary: Register a new user
      description: >
        Create a user with a name, preferred channel, and a list of available channels.
        The preferred channel must be one of the available channels.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Juan
                  description: The full name of the user
                preferred_channel:
                  type: string
                  enum: [email, sms, console]
                  example: email
                  description: The user's preferred notification channel
                available_channels:
                  type: array
                  items:
                    type: string
                    enum: [email, sms, console]
                  example:
                    - email
                    - sms
                  description: List of channels the user can receive notifications on
              required:
                - name
                - preferred_channel
                - available_channels
      responses:
        "201":
          description: User successfully registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Usuario Juan registrado."
                    description:  success message indicating registration
        "400":
          description: Bad request (e.g., missing fields or preferred channel not in list)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Falta nombre, canal preferido o canales disponibles"
                    description:  error message for missing data

    get:
      summary: List all users
      description: Retrieve a list of all registered users, including their preferred and available channels.
      responses:
        "200":
          description: Array of registered users
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          example: Juan
                          description: User's name
                        preferred_channel:
                          type: string
                          example: email
                          description: User's preferred channel
                        available_channels:
                          type: array
                          items:
                            type: string
                          example:
                            - email
                            - sms
                          description: List of channels available to user

  /notifications/send:
    post:
      summary: Send a notification to a user
      description: >
        Attempt to send a notification message to the specified user. 
        The system will first try the user’s preferred channel; if it fails, 
        it will move down the chain of available channels until delivery succeeds or all channels fail.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                  example: Juan
                  description: The name of the registered user
                message:
                  type: string
                  example: "Your appointment is tomorrow."
                  description: The notification message to send 
                priority:
                  type: string
                  enum: [low, normal, high]
                  example: high
                  description: The priority level of the notification
              required:
                - user_name
                - message
      responses:
        "200":
          description: Result of notification delivery attempts
          content:
            application/json:
              schema:
                type: object
                properties:
                  delivered:
                    type: boolean
                    example: true
                    description: Indicates if any channel succeeded
                  attempts:
                    type: array
                    description: List of each channel attempt and its outcome
                    items:
                      type: object
                      properties:
                        channel:
                          type: string
                          example: email
                          description: Channel that was attempted
                        success:
                          type: boolean
                          example: false
                          description: Whether that channel succeeded
                  priority:
                    type: string
                    example: high
                    description: The priority of the notification
        "400":
          description: Bad request (e.g., missing user_name or message)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Falta user_name o message"
                    description:  error message for missing fields
        "404":
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Usuario no encontrado"
                    description:  error message when user does not exist
